name: Test

on:
  schedule:
    - cron: '23 1 * * *'
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to checkout'
        required: true
        default: 'main'

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        testenv: ['test']
        include:
        - python-version: '3.10'
          testenv: 'black'
        - python-version: '3.10'
          testenv: 'codespell'
        - python-version: '3.10'
          testenv: 'flake8'
        - python-version: '3.10'
          testenv: 'lint'
        - python-version: '3.10'
          testenv: 'build-doc'
    steps:
    - uses: actions/checkout@main
      with:
        ref: ${{ github.event.inputs.ref }}
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install libclang
      if: matrix.testenv == 'build-doc'
      run: |
        sudo apt-get update
        sudo apt-get install libclang1-14
        # hack to get sphinx-c-autodoc to build C API documentation
        sudo ln -s /usr/lib/llvm-14/lib/libclang-14.so.1 /usr/lib/libclang-14.so
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Test with tox
      run: |
        tox -e ${{ matrix.testenv }}
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@main
      if: matrix.testenv == 'test'
      with:
        flags: ${{ matrix.python-version }}
    - name: Upload docs
      if: matrix.testenv == 'build-doc'
      uses: actions/upload-artifact@main
      with:
        name: docs
        path: docs/_build/html
  valgrind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        ref: ${{ github.event.inputs.ref }}
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@main
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install valgrind
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Test with tox
      run: |
        tox -e valgrind
  deploy-doc:
    runs-on: ubuntu-latest
    needs: tox
    if: >-
      github.event_name == 'push' &&
      (startsWith(github.event.ref, 'refs/tags') || github.event.ref == 'refs/heads/main')
    steps:
    - uses: actions/checkout@main
      with:
        ref: gh_pages
    - name: Setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - uses: actions/download-artifact@main
      with:
        name: docs
        path: docs/_build/html
    - name: Deploy doc
      run: |
        cp -r docs/_build/html/* docs/
        rm -rf docs/_build
        git add docs/
        git commit --author="Github Actions Bot <>" -m "Update docs" && \
            git push origin gh_pages || exit 0
